total_steps: 100000
dqfd_pretrain_steps: 20000
discrete: True
max_steps_per_traj: 1000

dqn: { learning_starts: 10000 }

cluster_config:
  {
    cluster_type: "kmeans",
    agglomerative_clustering_kwargs:
      { metric: "l2", linkage: "average", distance_threshold: 0.2 },
    kmeans_clustering_kwargs:
      { n_clusters: 100, max_iter: 300, algorithm: "lloyd" },
  }

prune_config:
  {
    prune_type: "value",
    group_filtering_kwargs:
      { size_threshold: 10, measure_cutoff: 80, method: "variance" },
    action_filtering_kwargs:
      {
        size_threshold: 10,
        measure_cutoff: 80,
        method: "variance",
        percentile: 50,
      },
    outcome_filtering_kwargs: { horizon: 10 },
  }
